### ISSUE TITLE
model "opaque types"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#335]
The goal here is to model Rust's `impl Trait`. For now the starting plan is to have a version where chalk is given both the opaque type declaration *and* the hidden type:

```rust
opaque type T<..>: Bounds = HiddenTy;
```

Note that opaque types can be generic.

We will model opaque types as an special kind of **alias**. Like associated types aliases, when an opaque type alias `T`  is equated with some other type `U`, we will generate an `AliasEq(T = U)` goal. 

The difference is that the two clauses for `AliasEq` goals work a bit differently. In particular, the "normalization" rule requires a special goal, `Reveal`, to be in the environment:

```rust
AliasEq(T = HiddenTy) :- Reveal.

AliasEq(T = !T).
```

There are also special rules for the `!T` placeholder:

```
Implemented(!T: Bounds). // from the declaration

// for auto traits:
Implemented(!T: AutoTrait) :- Implemented(HiddenTy: AutoTrait).
```
```

**Comment by nikomatsakis** [comment]
Let's create a check-list of details to take care of

* [ ] Add syntax for testing (included in #324)
* [ ] Add well-formedness checking rules for the definition (must prove that the hidden type implements the required bounds, assuming the where clauses)
* [ ] Extend so that the hidden type is lazily accessed -- this is needed to permit cyclic dependencies in cases where we don't need to prove that `$T: Send`, which rustc apparently supports (@flodiebold do you have an example test?)
* [ ] Extend with support for "where clauses" 
* [ ] Extend WF rules for implied bounds interactions

**Comment by flodiebold** [comment]
> (@flodiebold do you have an example test?)

How about [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ffa8c741bbd2c22cf0afea03788fe3c4) (comment in the `require_send` line to cause a cycle)?

**Comment by detrumi** [comment]
## Checklist
* [X] Add syntax for testing (#324)
* [X] Check that, without reveal, we can prove that the bounds are true but not other things (#324)
* [x] Cleanup debug output for impl traits (#400)
* [ ] Add tests for generic opaque types like `type Foo<X> = impl Iterator<Item = X>` (#402)
* [ ] Generate clauses for auto traits
* [ ] Check that, without reveal, we can prove that auto-traits hold if they hold for hidden type
* [ ] Check that, with reveal, we can prove equality and also prove all trait bounds we need to prove
* [ ] Add well-formedness checking rules for the definition (must prove that the hidden type implements the required bounds, assuming the where clauses)
* [ ] Extend so that the hidden type is lazily accessed -- this is needed to permit cyclic dependencies in cases where we don't need to prove that `$T: Send`, which rustc apparently supports (@flodiebold do you have an example test?)
* [ ] Extend with support for "where clauses" 
* [ ] Extend WF rules for implied bounds interactions
* [ ] Document opaque types in the chalk book

(moved the checklist to my own comment to avoid "nikomatsakis mentioned ..." messages when editing the checklist to refer to PRs)

**Comment by detrumi** [comment]
Only one task left: extend WF rules for implied bounds interactions. I can't quite remember what we meant with that, but I think it's something along these lines:

Given this program:
```
trait Clone { }
trait Iterator where Self: Clone { type Item; }
struct Struct { }
struct Ty { }

opaque type O: Iterator<Item = Struct> = Ty;
```
Using implied bounds, this can prove the following (see the [implied_bounds test](https://github.com/rust-lang/chalk/blob/758e38bf6ed84cfaa69ed24d469ca39f3e0f105c/tests/test/implied_bounds.rs#L5-L24)):
```
forall<T> {
    if (T: Iterator<Item = Struct>) {
        T: Clone
    }
}
```
The same should hold for opaque types, but doesn't:
```
if (Reveal) {
    O: Clone
}
```

We might be missing some more WF checks around opaque types, since the program above fails to prove the goal, but only does the WF check once you add `impl Iterator for Ty {}`
