### ISSUE TITLE
extend chalk `TypeName` with builtin types

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#368]
The [`TypeName`](http://rust-lang.github.io/chalk/chalk_ir/enum.TypeName.html) enum needs to be extended to cover the "built-in" types from Rust. The following variants would eventually want to be added:

* [x] scalar types:
  * [x] unsigned integer types (u32, u64, usize, etc)
  * [x] signed integer types
  * [x] bool
  * [x] char
* [x] tuple types (parameterized by arity, so `Tuple(usize)`)
* [x] str -- see https://github.com/rust-lang/chalk/issues/437
* [x] reference types `&` and `&mut` -- https://github.com/rust-lang/chalk/issues/438
* [x] raw pointer types `* const` and `*mut` -- https://github.com/rust-lang/chalk/issues/439
* [x] array types (requires const work to land)
* [x] slice type -- https://github.com/rust-lang/chalk/issues/440
* [x] `FnDef` (PR: https://github.com/rust-lang/chalk/pull/449)
* [x] `Never`
* [x] `Closure`
* [x] generator/ generator witness -- https://github.com/rust-lang/chalk/pull/593, https://github.com/rust-lang/chalk/issues/504
* [x] https://github.com/rust-lang/chalk/issues/453: generalize struct to enum/union
* [x] Support for multiple variants on `Adt` -- https://github.com/rust-lang/chalk/issues/505
* [x] Extern types -- https://github.com/rust-lang/chalk/issues/595

(Need to update this list, not yet complete, see [this section of the chalk book](http://rust-lang.github.io/chalk/book/types/rust_types.html#mapping-to-rustc-types) for a more complete list as well.

**Comment by MarkMcCaskey** [comment]
I'm interested in taking this on!  I'll follow up with a PR

**Comment by Areredify** [comment]
@MarkMcCaskey what's the status on this?

**Comment by MarkMcCaskey** [comment]
Sorry about the radio silence -- I've been busier than I anticipated recently and haven't had the spare focus to work on this.  I haven't worked on closures or functions other than what was in the original PR yet.  I can dedicate a bit of time to it this weekend and more time to it next week.  If this is blocking other issues and/or if someone wants to implement it, I have no problem with someone else taking it on but I'd be happy to work on it otherwise!

**Comment by nikomatsakis** [comment]
@rustbot release-assignment

I think @MarkMcCaskey is busy, but also I'm going to break this into distinct issues.

**Comment by nikomatsakis** [comment]
OK, I broke out a number of issues thus far that people can pick up.

**Comment by nikomatsakis** [comment]
@rustbot release-assignment

This is a tracking issue, so it doesn't really *need* an assignee.

**Comment by vringar** [comment]
Could this issue be closed and the remaining items moved into #16 directly so there's a more centralized overview of what still needs to be done for a shared type library?

**Comment by Mcat12** [comment]
@vringar Not sure if you linked to the right issue; that one is about checking kinds during lowering, from 2017.

**Comment by jackh726** [comment]
@vringar probably means rust-lang/wg-traits#16

I think keeping this open and linking to this from there is the best idea. Ultimately, yeah, there's not much left to here; but, I don't think it makes sense to put all the finer details there.

**Comment by vringar** [comment]
Sorry for fucking up the linking.
@jackh726 is right is the assumption but also in the resolution. 
Sorry for creating noise.

**Comment by jackh726** [comment]
@vringar No worries!

**Comment by Aaron1011** [comment]
With PR https://github.com/rust-lang/chalk/pull/593, we now have `Generator` and `GeneratorWitness`. All of the types in this issue are now checked off - is there anything left to do here?

**Comment by jackh726** [comment]
@Aaron1011 nothing left to do here

Thanks everyone for all the work to get this done :)

**Comment by LeSeulArtichaut** [comment]
Should the work item associated to this issue in #16 be checked?
