### ISSUE TITLE
move remaining vectors, boxes in chalk-ir into associated types on `Interner`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#369]
In general, we have been trying to remove hard-coded vectors and boxes from the chalk-ir APIs, and moving them instead to `Interner` associated types. See [the chalk book](http://rust-lang.github.io/chalk/book/types/role_of_interner.html) for more background on the `Interner` trait and its design. 

This issue tracks the removal of the final vectors etc:

* [x] `Vec<ProgramClause<I>>` in `Environment` -- introduce `ProgramClauses` -- done in #370
* [x] `Vec<QuantifiedWhereClause<I>>` in `DyTy` -- introduce `QuantifiedWhereClauses` -- done in #379
* [x] `Vec<Parameter>` in `Fn` (this should be changed to `Substitution`) -- done in #368 
* [ ] `Vec<ParameterKind<()>>` in `Binders`, `BindersIntoIterator` -- introduce `ParameterKinds` -- #386 
* [ ] `Vec<ParameterKind<Universe>>` in `Canonical` -- hmm, this one requires a bit of thought, because I think we want to reconcile other bits of canonicalization -- #386 

Here are some example PRs showing how this removal can be done:

* https://github.com/rust-lang/chalk/pull/316 converted a `Vec<Parameter>` into the `Substitution<I>` type
* https://github.com/rust-lang/chalk/pull/325 replaced `Vec<Goal<I>>` with `Goals<I>`

This issue has been assigned to @crlf0710 via [this comment](https://github.com/rust-lang/chalk/issues/369#issuecomment-612989155).

**Comment by crlf0710** [comment]
Will have a try this weekend.

**Comment by crlf0710** [comment]
Edit: Seems https://github.com/rust-lang/chalk/pull/370 is in flight.

**Comment by nikomatsakis** [comment]
@crlf0710 there are still other issues to claim -- e.g., `QuantifiedWhereClauses`, `ParameterKinds`, etc. Feel free to claim one of those.

**Comment by crlf0710** [comment]
Changed `Vec<Parameter>` to `Substitution` in `Fn` in #378. 

I'll have a try on `Vec<QuantifiedWhereClause<I>>` next.

**Comment by crlf0710** [comment]
Introduced `QuantifiedWhereClauses` in #379.

**Comment by crlf0710** [comment]
Given the rest a try in #386
